### ISSUE TITLE
composite.embeddedHandle is not part of the SWT public API

### ISSUE THREAD

**Issue by JMY1000** [caprica/vlcj-swt-swing#1]
On line 26 of CompositeVideoSurface.java, the component ID is retrieved using composite.embeddedHandle. [This field is not intended to be referenced by clients](http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.swt/org.eclipse.swt.gtk.aix.ppc/4.3/org/eclipse/swt/widgets/Composite.java#Composite.0embeddedHandle) and doesn't work under certain distributions, like cocoa.macosx.x86_64:4.3.

**Comment by caprica** [comment]
Yes, this is of course already known.

vlcj/LibVLC needs a heavyweight window handle.

What's your point and/or alternative?

**Comment by JMY1000** [comment]
[It appeared to be referenced in a macOS specific vlcj issue on getting things to work without heavyweight window handlers.](https://github.com/caprica/vlcj/issues/205) Is there something I'm missing with how to use this on macOS?

**Comment by caprica** [comment]
Unfortunately there is no approved cross-platform API to do what is needed on _any_ OS, so the only solution is to use some hacks like you've already found.

There is no getting away from the fact that if you want to use vlcj with the most optimal solution (directly rendering to a native window surface) then you _must_ obtain a valid heavyweight window handle from your UI toolkit. How you do that is implementation dependent. This applies whether you use Swing, SWT or anything else.

The real question here then is how to obtain a heavyweight window handle from SWT on Linux, Windows and OSX? This _example_ project shows how to do it on Linux.

If there was an API for this I would be using it already. I would be very happy if there was an alternative that someone would tell me about, but as far as I know there is nothing else.

I have seen some similar hacky code that uses reflection on OSX but at the moment I do not recall where I saw it, nor have I tried it myself.

**Comment by caprica** [comment]
The code I refer to above was something like this:

https://stackoverflow.com/questions/29889540/how-to-get-the-handle-of-swt-control-in-mac-64-bit-cocoa-enviornment

**Comment by caprica** [comment]
I was able to find the exact code I was referring to:

https://git.ricardorp.es/richie/vlcj

**Comment by JMY1000** [comment]
Gotcha. For now I've just gone with having my class draw the images as they come in.

**Comment by caprica** [comment]
That other code is at least worth a try, rendering the images yourself has a significant performance penalty.
